import json
import unittest
from pathlib import Path

from tests.twin_harness import REPO_ROOT, capture_state, run_twin
import main


REFERENCE_PATH = Path(__file__).resolve().parent / "data" / "preheater_lumped_reference.json"

EXPECTED_VALIDATIONS = {
    ("Burning", "energy"),
    ("Transition", "energy"),
    ("Calciner", "energy"),
    ("Cooler", "energy"),
    ("Preheater", "energy"),
    ("Preheater Stage 1", "energy"),
    ("Preheater Stage 2", "energy"),
    ("Preheater Stage 3", "energy"),
    ("Preheater Stage 4", "energy"),
    ("Preheater Stage 5", "energy"),
    ("Pyroprocess", "global_energy"),
    ("Pyroprocess", "global_mass"),
    ("Cooler", "air_split"),
    ("Pyroprocess", "global_co2_species"),
}


def assert_balances_pass(test, validations):

    reported = {(v["equipment"], v["balance_type"]) for v in validations}

    test.assertEqual(
        reported,
        EXPECTED_VALIDATIONS,
        "the set of balance checks run by Twin.run() changed",
    )

    for v in validations:
        with test.subTest(equipment=v["equipment"], balance=v["balance_type"]):
            result = v["result"]
            test.assertTrue(
                result["converged"],
                f"residual={result['residual']:.6e}, "
                f"relative={result['relative_residual']:.6e}, "
                f"abs_tol={result['absolute_tolerance']:.1e}, "
                f"rel_tol={result['relative_tolerance']:.1e}",
            )


class LumpedPreheaterRegressionTest(unittest.TestCase):
    """
    nodes_per_stage=1 must reproduce the lumped-stage preheater model
    bit for bit. The reference was generated by tests/twin_harness.py
    from commit 2991185, before the nodal stage model existed; do not
    regenerate it from the current code, which would make the test
    compare the model with itself.
    """

    @classmethod
    def setUpClass(cls):
        cls.twin, cls.validations = run_twin(nodes_per_stage=1)
        cls.snapshot = capture_state(cls.twin, cls.validations)
        cls.reference = json.loads(REFERENCE_PATH.read_text())["snapshot"]

    def test_snapshot_matches_lumped_reference_exactly(self):

        self.assertEqual(set(self.snapshot), set(self.reference))

        for key, expected in self.reference.items():
            with self.subTest(key=key):
                self.assertEqual(self.snapshot[key], expected)

    def test_balances_pass(self):
        assert_balances_pass(self, self.validations)


class NodalPreheaterBalanceTest(unittest.TestCase):
    """Default configuration: 20 co-current nodes per cyclone stage."""

    @classmethod
    def setUpClass(cls):
        cls.twin, cls.validations = run_twin()

    def test_default_is_20_nodes_per_stage(self):

        cfg = main.load_cfg(REPO_ROOT / "configs" / "twin_cfg.yaml")

        self.assertEqual(cfg["preheater"]["nodes_per_stage"], 20)
        self.assertEqual(self.twin.preheater.nodes_per_stage, 20)

        for stage in self.twin.preheater.stages:
            with self.subTest(stage=stage.stage_id):
                self.assertEqual(stage.node_gas_temperatures.size, 20)
                self.assertEqual(stage.node_solid_temperatures.size, 20)
                self.assertEqual(stage.node_wall_temperatures.size, 20)

    def test_balances_pass(self):
        assert_balances_pass(self, self.validations)

    def test_stage_node_profiles_end_at_stage_outlets(self):

        for stage in self.twin.preheater.stages:
            with self.subTest(stage=stage.stage_id):
                self.assertEqual(
                    stage.node_gas_temperatures[-1],
                    stage.gas_outlet_temperature,
                )
                self.assertEqual(
                    stage.node_solid_temperatures[-1],
                    stage.solid_outlet_temperature,
                )


if __name__ == "__main__":
    unittest.main()
